version: '2'

services:
  nginx-php-fpm:
    image: fmh
    build: .
    volumes:
    - "/Users/liyuequn/PhpstormProjects/fmh:/home/laravel"
    restart: always
    ports:
    - "8083:80"
    environment:
      WEBROOT: '/var/www/fmh'





