version: '2'

services:
  nginx-php-fpm:
    image: registry.cn-hangzhou.aliyuncs.com/liyuequn/liyuequn:1.0
    volumes:
    - "$PWD:/var/www/fmh"
    restart: always
    ports:
    - "8080:80"
    environment:
      WEBROOT: '/var/www/fmh'





