<?php
/**
 * Created by PhpStorm.
 * User: liyuequn
 * Date: 2018/8/6
 * Time: 上午1:11
 */

namespace Frame;
use Symfony\Component\HttpFoundation\Request as HttpRequest;

class Request extends HttpRequest
{
    public $route;

    public $method;

    public $request;

    public static function capture()
    {
        return self::createFromGlobals();
    }

    /**
     * @return string
     */
    public function getRoute()
    {
        $route = $this->getPathInfo();

        if($route!='/')
            $route = trim($route,'/');

        return $route;
    }

    /**
     * @return string
     */
    public function getMethod()
    {
        return $this->method = strtolower(parent::getMethod()); // TODO: Change the autogenerated stub
    }


}